CREATE TABLE IF NOT EXISTS teacher
(
    id            INT PRIMARY KEY AUTO_INCREMENT,
    creation_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted       DATETIME
) ENGINE InnoDB
  CHAR SET UTF8MB4;
